#!/usr/bin/perl -w

use NewsMonitor;

use UniLang::Agent::Agent;
use UniLang::Util::Message;

$UNIVERSAL::agent = UniLang::Agent::Agent->new
  (Name => "NewsMonitor",
   ReceiveHandler => \&Receive);
$UNIVERSAL::newsmonitor = NewsMonitor->new();

sub Receive {
  my %args = @_;
  $UNIVERSAL::newsmonitor->ProcessMessage
    (Message => $args{Message});
}

$UNIVERSAL::newsmonitor->Execute();
